# Generated by Django 3.2.5 on 2021-07-28 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='GroupId',
            new_name='group',
        ),
    ]
